# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT349 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.4.9"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.9/cq-scaffold_darwin_amd64.zip"
      sha256 "66fbe4c352ed93d8394b123a46af50aeb80a230b3f83935f36b65744250b7c2c"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.9/cq-scaffold_darwin_arm64.zip"
      sha256 "0bea8ab6be96d3bdc2a9fb6fcde3aaadaf795546ed93478907fcb912acb9dc51"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.9/cq-scaffold_linux_amd64.zip"
        sha256 "c0a52c9bec847bf3e69a18047cc65a16aa8e0b3dab2423925be94155471427e8"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.9/cq-scaffold_linux_arm64.zip"
        sha256 "1bde1766d6ae80389194d60193fdc134418065f6f497171ee162c90de70c5430"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
