# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT320 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.2.0"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.2.0/cq-scaffold_darwin_amd64.zip"
      sha256 "21ee14845518bcb4923134295272fa5f0ba22a99a5cd274b7ccb231a7337dab8"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.2.0/cq-scaffold_darwin_arm64.zip"
      sha256 "9f6a71f80ae68ec075993a546a16368f090dfeceefb0cac890f71165247a010f"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.2.0/cq-scaffold_linux_amd64.zip"
        sha256 "5265ece13ab85048a5fa2579805237552e0c61bcb2fd29ca00d7380fc2609814"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.2.0/cq-scaffold_linux_arm64.zip"
        sha256 "812067fefaf5e0cc6356df9a428b32dfb837c98358c4891a6a4e4768aaabbcc2"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
