# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3411 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.4.11"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.11/cq-scaffold_darwin_amd64.zip"
      sha256 "7cf1be97bcf73989df2af601d0f4b7ed719a858a7938396a0da502e646c23af5"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.11/cq-scaffold_darwin_arm64.zip"
      sha256 "7abfb7e550fe7f1497e6e8a3939a7b992b01cfe57f975c7e41a0781a888764d0"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.11/cq-scaffold_linux_amd64.zip"
        sha256 "5bb0d621dd2d222c9242fe7f76319408abac9e18ad184c785ffc2fd469738171"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.11/cq-scaffold_linux_arm64.zip"
        sha256 "de4cc4af5e7b865f4ff546c62f43dcd522a2fd434602c6fd57dfaaa6c558a212"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
