# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT214 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "2.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.4/cq-scaffold_darwin_amd64.zip"
      sha256 "52c3a6df8a524747aa92db0c6708fa69ddc3b874430d41b4e3324008311feeec"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.4/cq-scaffold_darwin_arm64.zip"
      sha256 "e9a646089f7ff8c0857da05d31471a3e5cc95f23ae9e55fd91964e1f1fc0eaba"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.4/cq-scaffold_linux_arm64.zip"
      sha256 "9d85e16bf55cbb4affa74bf5dffc54122a8f39d434952a6a14d9b6755c35b5ce"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.4/cq-scaffold_linux_amd64.zip"
      sha256 "926a911193f7983883f62d69090dc415a84b3aa8d798f4d8c233a8a68d1115eb"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
