# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3438 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.4.38"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.38/cq-scaffold_darwin_amd64.zip"
      sha256 "f9afc2cfaa66c0ef2bbdf5a6d04b147b37c4e3d39ddc07af94dd06f78de5d5af"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.38/cq-scaffold_darwin_arm64.zip"
      sha256 "e7ade175c5b6d7088497dae4fd5b862ed2829cefc7d23e15aa31de3684a5e2d2"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.38/cq-scaffold_linux_amd64.zip"
        sha256 "f3f8298551976f97744aa368d6a93022d03a46824dd5dae502453825f032a6a4"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.38/cq-scaffold_linux_arm64.zip"
        sha256 "ac4f0e754bade8d972fe79c3d753602fa2252b414c613488db3793775837c628"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
