# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3018 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.0.18"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.18/cq-scaffold_darwin_amd64.zip"
      sha256 "bf9184940ac4bc05ae8d30953bd9da71f8e1056cf8bf82da93ac1c4e25a8c2d1"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.18/cq-scaffold_darwin_arm64.zip"
      sha256 "805812d2fef0fbe25a1d1d0439de8db0594489471d5f060037fdc7db5da45ef7"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.18/cq-scaffold_linux_amd64.zip"
        sha256 "1cd291679c8608d3cdeedd8ebbc4c5892e53a5305257b3be766463bbae25d73e"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.18/cq-scaffold_linux_arm64.zip"
        sha256 "5ea33995e7b7e93184f1c3c3fff9de4282f59f9b36c8adbd5648ef7150685fee"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
