# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT165 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "1.6.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.6.5/cq-scaffold_darwin_amd64.zip"
      sha256 "38609d98a17ea321e29d73f2b4125cd9ae05e526916bf8e2170a609c553c0d81"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.6.5/cq-scaffold_darwin_arm64.zip"
      sha256 "edcdc9ffdabaa5c0e657a5bef02f23af07b06f99a13fded247075efbbdb9401a"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.6.5/cq-scaffold_linux_amd64.zip"
      sha256 "5c40c0a0584231b63a772c8cf911e1032af58f162209c088252b3a61f07dd91e"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.6.5/cq-scaffold_linux_arm64.zip"
      sha256 "9c3eab89c2e7821d2ac01ba1193851613f658106e443cefd921dc55564f61a07"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
