# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT344 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.4.4"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.4/cq-scaffold_darwin_amd64.zip"
      sha256 "0a8807111e525a6d8802a96fe4ea31ec9ef0970b460056a86e143b6f0783be3a"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.4/cq-scaffold_darwin_arm64.zip"
      sha256 "adfcefef898c166faa077f3bff4f92ba5be94d64e1c0af878a5274f3d7db6608"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.4/cq-scaffold_linux_amd64.zip"
        sha256 "82f54c21732a59744cc9854cf0b4652a1030e221c471ef41350697473fe33eb2"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.4/cq-scaffold_linux_arm64.zip"
        sha256 "162fdca1674f3e55578fa9ffbd31547db0845d79842b8490db16a67a40d57799"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
