# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT166 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "1.6.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.6.6/cq-scaffold_darwin_arm64.zip"
      sha256 "5ee8dccaf961543cd5b985a5325bcfdf29bf5ac12fbe5e731f10d84199d26572"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.6.6/cq-scaffold_darwin_amd64.zip"
      sha256 "2b7a4cc3cf29fea4be813b2422ff2f4d9c6c83ee4ea87172abdd941d76a2331d"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.6.6/cq-scaffold_linux_amd64.zip"
      sha256 "aaa89b494e5658a38d7557e487873ddd37e5e11abdfa42fbff3a400aba6e4510"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.6.6/cq-scaffold_linux_arm64.zip"
      sha256 "9ca865ba8633b8ccd57f7a7fd7757e3e34d922eaa81aa38efaac741f524b6753"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
