# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3017 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.0.17"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.17/cq-scaffold_darwin_amd64.zip"
      sha256 "bdaf02cc1059ae2bb49661cd48f5072734a4f2438faff1add8b064aa72e841f8"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.17/cq-scaffold_darwin_arm64.zip"
      sha256 "2c70f5e747ce0d1802c21a7bf12fca407cbcc0ad985e652400888ffe9050bacf"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.17/cq-scaffold_linux_amd64.zip"
        sha256 "bf4c84eda149443c65105dc876ddb7d0d48651162be3305a340bcc1af8b1b9b5"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.17/cq-scaffold_linux_arm64.zip"
        sha256 "e046cb34461b29db2f7532f9f7bd5b44ce25e166da0e11ce90e99157f9e1f353"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
