# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT310 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.1.0"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.1.0/cq-scaffold_darwin_amd64.zip"
      sha256 "7c962cb95ab3273eda72c7ef6fef95d2392743a3f589facff38fe35a790dacfb"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.1.0/cq-scaffold_darwin_arm64.zip"
      sha256 "b54fcc97dde84dc1e7d26bd5e44d2074f1ab5568326ae4f52d62ff49a23ddf10"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.1.0/cq-scaffold_linux_amd64.zip"
        sha256 "f7fc956a3e790bff1bfc2ebfb809073afadd4a0ccd9611e85dc64efa1fbc5b3a"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.1.0/cq-scaffold_linux_arm64.zip"
        sha256 "ec39c42428c73002531c0785297b91648377eb22a7a06018e7c18511a5702997"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
