# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3013 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.13/cq-scaffold_darwin_amd64.zip"
      sha256 "6a0cbffa6ca5ac00e841247bdb31e44d241e8729977ead5b88ae42c0c1d43754"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.13/cq-scaffold_darwin_arm64.zip"
      sha256 "d87782c8fa1492d6d2aa1ca9f332f79753b4bca4c782028f3db897bac4dd5d37"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.13/cq-scaffold_linux_amd64.zip"
      sha256 "9d23ec9dce34f40639617c102b43ac1f2044380d72783d872320288a41161383"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.13/cq-scaffold_linux_arm64.zip"
      sha256 "7e7fb05edd6779fa93cf9f0d25adb78ecff0bbc8bb94d7722e645528f2879f3d"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
