# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT212 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "2.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.2/cq-scaffold_darwin_arm64.zip"
      sha256 "6b2fd1b411fcf5f0500cf41d2f82e5362d4aafbc5b8925e1d70cf8e459ce027d"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.2/cq-scaffold_darwin_amd64.zip"
      sha256 "6935b0d5dcac31e6b260cc3aecabb5cc0e99e9b319beb0f78066ce1b1b05ce7e"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.2/cq-scaffold_linux_arm64.zip"
      sha256 "8a9990c8fb21fa51e5fee06f50a6a3bcdfef635d56d8e1f57eeccb350eb53800"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.2/cq-scaffold_linux_amd64.zip"
      sha256 "e1942b42fb861b15235ec31c6becf0a691318a9bf439e9e5647ca72f19868823"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
