# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT313 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.1.3"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.1.3/cq-scaffold_darwin_amd64.zip"
      sha256 "e058643516a76d4f788bf2053c840a43bba0ddb596d9a94cbc054cbbc3cefae7"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.1.3/cq-scaffold_darwin_arm64.zip"
      sha256 "c6ce4a1448982f31e8ba05607051fa2c5b09d47e67f90572964539ccb68db3d9"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.1.3/cq-scaffold_linux_amd64.zip"
        sha256 "56556d375c09e536844d99d7324f88b47a4f7295a3d92c553d1ea19a30de667b"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.1.3/cq-scaffold_linux_arm64.zip"
        sha256 "9d9b618b1e719ba3eee1d4bc6e17629defd04be4ff2e29a7aa3d32cc8297b566"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
