# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3416 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.4.16"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.16/cq-scaffold_darwin_amd64.zip"
      sha256 "b2cbd0a3a4bec342d7bf4eeecfb1e03a24c894aeec586742c20bc950af52bd8f"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.16/cq-scaffold_darwin_arm64.zip"
      sha256 "f172c1d58420709c8902d9e2d495064fbccf462b47c019ff477b03440b358135"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.16/cq-scaffold_linux_amd64.zip"
        sha256 "68c6b3d568a7cafb6bd2fbc691e5cf20c35c2de4c0096e2fe7244ab28b875ed5"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.16/cq-scaffold_linux_arm64.zip"
        sha256 "dad678f3c88b4ef501ed27160bf3bdd41c46c6b22daa8cfa9f2de67c32b61f4b"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
