# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffold < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "2.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.11/cq-scaffold_darwin_amd64.zip"
      sha256 "52541c50f79b4ac5b876330b943c3972d2edd6aa77bb0dea87f90307c4e1acb2"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.11/cq-scaffold_darwin_arm64.zip"
      sha256 "bbd3efb6de77c2d512cdb0822ffa05d78513122de2543a36427fb9252b8227aa"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.11/cq-scaffold_linux_arm64.zip"
      sha256 "034c21c88615279c1fd8a618f107d9d4f7d6667d528b9aa05f00cd698ccf3e1f"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.11/cq-scaffold_linux_amd64.zip"
      sha256 "e7192938cd71b0da6b2cf17e5ad56d5a8adf7a1bd7d0d1cb2ed9a15f2e1d1101"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
