# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3015 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.0.15"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.15/cq-scaffold_darwin_amd64.zip"
      sha256 "2de1e35f03d67386a6c981a277287ce15d6343bacbc5582812be0c607540c748"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.15/cq-scaffold_darwin_arm64.zip"
      sha256 "183600d2b1c88f1a2757b8cd51b887c213dcb5375da87faea424d3680430f825"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.15/cq-scaffold_linux_amd64.zip"
        sha256 "b198589913dfc884f9593dc85a259a751607fa0452f252c6c03c6ab776447343"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.15/cq-scaffold_linux_arm64.zip"
        sha256 "6a93eed19a97620d1ebaafa25163bce5862fcf708fce6faebfbd7e95fe0855a7"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
