# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT152 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "1.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.5.2/cq-scaffold_darwin_amd64.zip"
      sha256 "3d7fa2f2f3ec507cd74062ea8c6c1b5fd5e05ce124bcfab73b4250e663e20459"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.5.2/cq-scaffold_darwin_arm64.zip"
      sha256 "ecbfe99f1ca930ed4ae7d983dfda1a123790b5bb99dedbb889978f27b82b0996"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.5.2/cq-scaffold_linux_arm64.zip"
      sha256 "6c3461a3e35f9344b2777c503edfabfefa001e79ea38b0bd4b02cc5be41fb961"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v1.5.2/cq-scaffold_linux_amd64.zip"
      sha256 "cadd171473e9de90dde15b89fd08941282d7ec8b20cbe819ddf1281b5d38bef1"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
