# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT2113 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "2.1.13"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.13/cq-scaffold_darwin_arm64.zip"
      sha256 "1beba4ab948ceb1401503135ef3b7e97fa92b1ae169970292bfaaee7e3a64380"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.13/cq-scaffold_darwin_amd64.zip"
      sha256 "051cab72f4c1241890b3315c7d22a8a0b80340abbc60d3306fdece26141aa62d"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.13/cq-scaffold_linux_amd64.zip"
      sha256 "6b257ee56da2ca874f1c71bb5672060d61e667aecf26d7ebf2f0dcb879f36490"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.1.13/cq-scaffold_linux_arm64.zip"
      sha256 "a3353d4d931ad7b087f03533a6389c46994789d0af4dc9fdfef816a0b75184fa"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
