# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT201 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "2.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.0.1/cq-scaffold_darwin_amd64.zip"
      sha256 "7c87291af196e4361b90ada3db4deb6f036d7c45dcb3442cda6548e644c2466c"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.0.1/cq-scaffold_darwin_arm64.zip"
      sha256 "fa0daadd7fba5b953de10037a364a08fe8693a8602dc95e3616ef5c4834521a3"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.0.1/cq-scaffold_linux_arm64.zip"
      sha256 "702bdd1bf45067a4addd27bfd70b8d7bb530e645426e10710cc10ecfb3422f7b"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.0.1/cq-scaffold_linux_amd64.zip"
      sha256 "207ff27acae9e05b14d804ad06974908824b8960c5ca75a94e89fce6858341bb"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
