# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3441 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.4.41"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.41/cq-scaffold_darwin_amd64.zip"
      sha256 "f8ee12627eee8220727bf187c3cea365eceae25afb0ab3e6b10f4aeaca73fa9a"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.41/cq-scaffold_darwin_arm64.zip"
      sha256 "ea482d495c28d08b5a5453b8684383f1c8d9372f2b92b842a011b90add51bccc"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.41/cq-scaffold_linux_amd64.zip"
      sha256 "3eff7df577a41728ebed561576ae5b44e1716fe0aab9ee59c9b28e10da8c385f"
      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.41/cq-scaffold_linux_arm64.zip"
      sha256 "ac6d291a1f88bbe1ad1c7af64122fbdb3cee19e0b4c4aecf62ddf338fc621c37"
      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
