# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3427 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.4.27"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.27/cq-scaffold_darwin_amd64.zip"
      sha256 "f34295abb5db2db2e2cefb903167f7f00c92cb471e68ef47e1986860e8cf1113"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.27/cq-scaffold_darwin_arm64.zip"
      sha256 "70c98ca13f2beef9d3227f5ebf2f546ed80ad61d6a32001084ab4b33e3c79336"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.27/cq-scaffold_linux_amd64.zip"
        sha256 "ae22346fb067f68b73b7370f232e1f7244cb5ee6906aab5197ab722193685350"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.27/cq-scaffold_linux_arm64.zip"
        sha256 "eac652b1f3ad9f1fa20bd45944d0f8c174432ec701641d1ce1b062d74b80b0cd"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
