# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT200 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.0.0/cq-scaffold_darwin_amd64.zip"
      sha256 "e1759d5d46c88a419452a433f36abfeed94f8cdd253c76900be18601deb74554"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.0.0/cq-scaffold_darwin_arm64.zip"
      sha256 "2a20c38d4600844df4585103ca3b19b08565dd2e3090be8df69165fd0d50925f"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.0.0/cq-scaffold_linux_arm64.zip"
      sha256 "fd538c22c65af7e34e2dfdbf63d06674ec4011db93d58d26985f7bcf29784704"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v2.0.0/cq-scaffold_linux_amd64.zip"
      sha256 "e28d9025fd1da25ae1d5da8ea8eca1c63609de55160f6627dfdba75c52ecf908"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
