# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT330 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.3.0"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.3.0/cq-scaffold_darwin_amd64.zip"
      sha256 "91958930253e68e9229eeee5bf50f8c2c4e45b6fdd4f883cdca9828ead19ff49"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.3.0/cq-scaffold_darwin_arm64.zip"
      sha256 "98a89ebf540cabb4231e417752f7425fb8433343f7fa85322efc44fbed19c622"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.3.0/cq-scaffold_linux_amd64.zip"
        sha256 "a718d350ba095f3b92538fd203e00f40a03653da72efb8a4f37a9e1bbbd65228"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.3.0/cq-scaffold_linux_arm64.zip"
        sha256 "751cba2c9fabbec6194276b01e6ed887c43af0377c0af6f2d8ef95e9251548f9"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
