# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT3428 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.4.28"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.28/cq-scaffold_darwin_amd64.zip"
      sha256 "81ba865b25fc689944acd86976da8767c3aa057853c124fe1a24ac10323562c9"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.28/cq-scaffold_darwin_arm64.zip"
      sha256 "f225988b3f49c3d00c207041502bd3a8d4f8e5745618868ba53d94aea9ed04aa"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.28/cq-scaffold_linux_amd64.zip"
        sha256 "8a5418db80ec768bcbe6e1e46d26aae7267ffb31803b1a16a7b213b64b72f436"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.28/cq-scaffold_linux_arm64.zip"
        sha256 "75eeee257b41c2a8908556c95910ed5fcd41990f751c4ab7e345f219cde95e8a"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
