# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT300 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.0/cq-scaffold_darwin_arm64.zip"
      sha256 "7158f9fce44fda33ea01b0e06b7b3e31bc1fdb1b563d801a6215bd18f20d50cb"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.0/cq-scaffold_darwin_amd64.zip"
      sha256 "842720c10fecc3ff3271506ad81ce5a626eef344a2cb8c6f437ee8c5184de473"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.0/cq-scaffold_linux_amd64.zip"
      sha256 "39cb5e36a8c0f840951d5e27c9050e2c14a4a6e74722f75e87ed3d1eade73761"

      def install
        bin.install "cq-scaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.0.0/cq-scaffold_linux_arm64.zip"
      sha256 "4311fc34dcc1bbde822be389c46008c681ab63b18b1a79d6145e5481bc8e6669"

      def install
        bin.install "cq-scaffold"
      end
    end
  end
end
