# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaffoldAT345 < Formula
  desc "Scaffold CloudQuery source and destination plugins"
  homepage "https://cloudquery.io"
  version "3.4.5"

  on_macos do
    on_intel do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.5/cq-scaffold_darwin_amd64.zip"
      sha256 "e0fa085168303a7703834494eab49810df41f69d82b9af2cb36e94927d612903"

      def install
        bin.install "cq-scaffold"
      end
    end
    on_arm do
      url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.5/cq-scaffold_darwin_arm64.zip"
      sha256 "c44e008002d2189fbd96a43035fc4917ef8d183c6e97f76dcefbfc09218d783b"

      def install
        bin.install "cq-scaffold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.5/cq-scaffold_linux_amd64.zip"
        sha256 "f7ccf54f8a803d2b5cd52ef5b99cfefea5a1fa0879ed1a4e02ec3c82f92fdbf3"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudquery/cloudquery/releases/download/scaffold-v3.4.5/cq-scaffold_linux_arm64.zip"
        sha256 "49b83491f1c41876473ce3e4ae0c3c2ce5c921d02fdc31df180398a38437b02b"

        def install
          bin.install "cq-scaffold"
        end
      end
    end
  end
end
